version: '3.8'

name: telegram_casino_backend

services:
  api.casino:
    container_name: api_casino
    hostname: api.casino
    build:
      context: ./API.Casino
    restart: on-failure
    networks:
      - backend
    depends_on:
      - rabbitmq

  api.gateway:
    container_name: api.gateway
    build:
      context: ./API.Gateway
    ports:
      - "8001:80"
    restart: on-failure
    depends_on:
      - api.casino
    networks:
      - backend

  worker.telegram:
    container_name: worker_telegram
    build:
      context: ./Worker.Telegram
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - backend

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: on-failure
    networks:
      - backend

networks:
  backend:
    driver: bridge
