version: '3.8'

name: telegram_casino_backend

services:
  api.casino:
    container_name: api_casino
    hostname: api.casino
    build:
      context: ./API.Casino
    restart: on-failure
    networks:
      - backend

  api.gateway:
    container_name: ap
    build:
      context: ./API.Gateway
    ports:
      - "8001:80"
    restart: on-failure
    networks:
      - backend
    depends_on:
      - api.casino

  worker.telegram:
    build:
      context: ./Worker.Telegram
    restart: on-failure

networks:
  backend:
    driver: bridge
